# Generated by Django 5.0.7 on 2024-07-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
