# Generated by Django 5.0.7 on 2024-07-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0002_rename_adress_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
